version: "3"
services:
  phpfpm:
    build:
      context: docker/php
      dockerfile: ${DOCKER_FILE}
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    hostname: ${COMPOSE_PROJECT_NAME}-fpm
    environment:
      - APP_TIMEZONE=${APP_TIMEZONE}
      - PHP_ERROR_REPORTING_LEVEL_INT=${PHP_ERROR_REPORTING_LEVEL_INT}
      - PHP_VERSION=${PHP_VERSION}
      - COMPOSER_HOME=/var/www/.composer
    volumes:
      - ./src:/app
      - ./.env:/app/.env
      - ./tests/php:/app/tests
      - ./docker/php/conf/www.conf:/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf
      - ./docker/php/conf/php-fpm.conf:/etc/php/${PHP_VERSION}/fpm/php-fpm.conf
      - ./docker/tmp/composer:/var/www/.composer
      - ./xdebug:/xdebug
    networks:
      default:
    restart: always

  web:
    image: objectsystems/nginx:1.19.2
    container_name: ${COMPOSE_PROJECT_NAME}-web
    hostname: ${COMPOSE_PROJECT_NAME}-web
    environment:
      - WEB_HOST_NAME=${WEB_HOST_NAME}
    volumes:
      - ./src:/app
      - ./.env:/app/.env
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/restrict.conf:/etc/nginx/snippets/restrict.conf
      - ./docker/nginx/web.template:/etc/nginx/conf.d/default.template
    links:
      - "phpfpm"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.`${COMPOSE_PROJECT_NAME}`.entrypoints=web-secure"
      - "traefik.http.routers.`${COMPOSE_PROJECT_NAME}`.rule=Host(`${WEB_HOST_NAME}`)"
      - "traefik.http.routers.`${COMPOSE_PROJECT_NAME}`.tls=true"
    command: /bin/bash -c "envsubst '$$WEB_HOST_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && /opt/wait.sh && nginx -g 'daemon off;'"
    networks:
      default:
    restart: always

networks:
  default:
    external:
      name: osinet
